version: '3.8'

services:
  maven:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    command: mvn clean compile test xray:import-results -Dmaven.test.failure.ignore=true
    environment:
      - MAVEN_OPTS=-Xmx512m
    depends_on:
      - selenium

  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    environment:
      - SELENIUM_URL=http://selenium:4444/wd/hub